name: Node Github CI/CD

on:
   push:
      branches:
         - production

jobs:
   test:

      runs-on: ubuntu-latest

      strategy:
        matrix:
           node-version: [16.x, 18.x]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/set-node@v1
          with: 
            node-version: ${{ matrix.node-version }}
        - name: running test
          run:
            yarn install
            yarn run
          env:
           CI: true